-- Create the CMS tables required by the ANJK UI
-- Run this in the Supabase SQL Editor.

create table if not exists public."HomePageContents" (
  "Id" bigint generated by default as identity primary key,
  "HeroTitle" text,
  "HeroSubtitle" text,
  "WelcomeSection" text,
  "AboutSection" text,
  "FeaturedContent" text,
  "HomeImages" jsonb not null default '[]'::jsonb,
  "Announcements" text
);

create table if not exists public."ContactSettings" (
  "Id" bigint generated by default as identity primary key,
  "Email" text,
  "PhoneNumber" text,
  "Address" text,
  "FacebookUrl" text,
  "InstagramUrl" text,
  "YoutubeUrl" text,
  "WhatsappNumber" text,
  "FooterTitle" text,
  "CopyrightText" text,
  "QuickLinks" jsonb not null default '[]'::jsonb
);

alter table if exists public."HomePageContents" enable row level security;
alter table if exists public."ContactSettings" enable row level security;

drop policy if exists "public read HomePageContents" on public."HomePageContents";
drop policy if exists "admin write HomePageContents" on public."HomePageContents";
drop policy if exists "public read ContactSettings" on public."ContactSettings";
drop policy if exists "admin write ContactSettings" on public."ContactSettings";

create policy "public read HomePageContents"
  on public."HomePageContents"
  for select
  using (true);

create policy "admin write HomePageContents"
  on public."HomePageContents"
  for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "public read ContactSettings"
  on public."ContactSettings"
  for select
  using (true);

create policy "admin write ContactSettings"
  on public."ContactSettings"
  for all
  using (public.is_admin())
  with check (public.is_admin());

grant select on public."HomePageContents" to anon, authenticated;
grant select on public."ContactSettings" to anon, authenticated;
grant insert, update, delete on public."HomePageContents" to authenticated;
grant insert, update, delete on public."ContactSettings" to authenticated;

insert into public."HomePageContents"
  ("HeroTitle", "HeroSubtitle", "WelcomeSection", "AboutSection", "FeaturedContent", "HomeImages", "Announcements")
select
  'Anjigeri Naad Koota',
  'Community. Sport. Heritage.',
  'Welcome to ANK. Stay connected with events, stories, and live updates.',
  'A bold home for Kodava heritage, competitive sport, village unity, and club history.',
  'Latest club highlights and announcements appear here.',
  '[]'::jsonb,
  ''
where not exists (select 1 from public."HomePageContents");

insert into public."ContactSettings"
  ("Email", "PhoneNumber", "Address", "FacebookUrl", "InstagramUrl", "YoutubeUrl", "WhatsappNumber", "FooterTitle", "CopyrightText", "QuickLinks")
select
  'anjigerinaad@gmail.com',
  '',
  '',
  '',
  '',
  '',
  '',
  'Anjigeri Naada',
  'Copyright © Anjigeri Naad Koota',
  '[{"label":"Home","path":"/"},{"label":"Villages","path":"/villages"},{"label":"Events","path":"/events"},{"label":"Sports","path":"/sports"},{"label":"Gallery","path":"/gallery"},{"label":"Contact","path":"/contact"}]'::jsonb
where not exists (select 1 from public."ContactSettings");

notify pgrst, 'reload schema';
