services:
  - type: web
    name: anjk-api
    env: docker
    rootDir: ANJK/anjk_api
    autoDeploy: true
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
