using anjk_api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;

namespace anjk_api.Data
{
    public static class SeedData
    {
        public static void Seed(AppDbContext context)
        {
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""AboutSections"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Title"" character varying(200) NOT NULL,
                    ""Body"" text NOT NULL,
                    ""SortOrder"" integer NOT NULL DEFAULT 0,
                    ""IsActive"" boolean NOT NULL DEFAULT true
                );");

            if (!context.AboutSections.Any())
            {
                context.AboutSections.AddRange(
                    new AboutSection
                    {
                        Title = "Who We Are",
                        Body = "Anjigeri Naad Koota is rooted in the Kodagu (Coorg) tradition of a Naad, bringing together families, athletes, and community members from the Anjigeri region.",
                        SortOrder = 1,
                        IsActive = true
                    },
                    new AboutSection
                    {
                        Title = "Sports and Unity",
                        Body = "The club is best known for sporting unity, especially in Kodava hockey through the Kodava Hockey Premier League, where the Anjigeri Naad team represents shared community strength.",
                        SortOrder = 2,
                        IsActive = true
                    },
                    new AboutSection
                    {
                        Title = "Community Focus",
                        Body = "We support youth development, live match updates, membership, and local events that strengthen social cohesion across the Kodava community.",
                        SortOrder = 3,
                        IsActive = true
                    }
                );
            }

            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""SportTournamentRecords"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Title"" character varying(120) NOT NULL,
                    ""SportName"" character varying(40) NOT NULL,
                    ""ActivityType"" character varying(20) NOT NULL,
                    ""RecordState"" character varying(20) NOT NULL,
                    ""EventDate"" timestamp with time zone NOT NULL,
                    ""Venue"" character varying(180) NOT NULL DEFAULT '',
                    ""OpponentOrHost"" character varying(180) NOT NULL DEFAULT '',
                    ""Description"" text NOT NULL DEFAULT '',
                    ""Result"" character varying(120) NOT NULL DEFAULT '',
                    ""SortOrder"" integer NOT NULL DEFAULT 0
                );");

            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""LiveUpdates"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Message"" character varying(500) NOT NULL,
                    ""CreatedOn"" timestamp with time zone NOT NULL DEFAULT NOW()
                );");

            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""Achievements"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Title"" character varying(200) NOT NULL,
                    ""Description"" text NOT NULL,
                    ""AwardedOn"" timestamp with time zone NOT NULL
                );");

            if (!context.SportTournamentRecords.Any())
            {
                context.SportTournamentRecords.AddRange(
                    new SportTournamentRecord
                    {
                        Title = "Kodava Hockey League - Match Run",
                        SportName = "Hockey",
                        ActivityType = "Played",
                        RecordState = "History",
                        EventDate = DateTime.UtcNow.AddMonths(-6),
                        Venue = "Madikeri Ground",
                        OpponentOrHost = "Local Club",
                        Description = "ANJ played a competitive hockey match in the regional league.",
                        Result = "Won 2-1",
                        SortOrder = 1
                    },
                    new SportTournamentRecord
                    {
                        Title = "District Cricket Cup",
                        SportName = "Cricket",
                        ActivityType = "Played",
                        RecordState = "Live",
                        EventDate = DateTime.UtcNow,
                        Venue = "Kushalnagar Stadium",
                        OpponentOrHost = "District XI",
                        Description = "ANJ is currently participating in the district cricket cup.",
                        Result = "In Progress",
                        SortOrder = 2
                    },
                    new SportTournamentRecord
                    {
                        Title = "ANJ Summer Football Fest",
                        SportName = "Football",
                        ActivityType = "Hosted",
                        RecordState = "History",
                        EventDate = DateTime.UtcNow.AddMonths(-3),
                        Venue = "Community Ground",
                        OpponentOrHost = "Hosted by ANJ",
                        Description = "Hosted a football festival for nearby teams.",
                        Result = "Successful Event",
                        SortOrder = 3
                    },
                    new SportTournamentRecord
                    {
                        Title = "Anjigeri Marathon Meet",
                        SportName = "Marathon",
                        ActivityType = "Hosted",
                        RecordState = "Live",
                        EventDate = DateTime.UtcNow.AddDays(10),
                        Venue = "Village Road Loop",
                        OpponentOrHost = "Hosted by ANJ",
                        Description = "Upcoming marathon event being hosted by the club.",
                        Result = "Upcoming",
                        SortOrder = 4
                    }
                );
            }

            if (context.AppUsers.Any())
            {
                var existingGeneralUsers = context.AppUsers.Where(user => user.Role == "Member").ToList();
                foreach (var user in existingGeneralUsers)
                {
                    user.Role = "General Public";
                }

                context.SaveChanges();
                return;
            }

            var admin = new AppUser
            {
                FullName = "ANK Admin",
                Email = "admin@ank.org",
                Role = "Admin",
                MembershipStatus = "Active",
                MembershipExpires = DateTime.UtcNow.AddYears(1),
                PasswordHash = ""
            };
            var member = new AppUser
            {
                FullName = "Rahul Kumar",
                Email = "rahul@ank.org",
                Role = "General Public",
                MembershipStatus = "Active",
                MembershipExpires = DateTime.UtcNow.AddYears(1),
                PasswordHash = ""
            };

            var passwordHasher = new Microsoft.AspNetCore.Identity.PasswordHasher<AppUser>();
            admin.PasswordHash = passwordHasher.HashPassword(admin, "Admin123!");
            member.PasswordHash = passwordHasher.HashPassword(member, "Member123!");

            context.AppUsers.AddRange(admin, member);

            context.SaveChanges();
        }
    }
}
