using anjk_api.Live;
using anjk_api.Data;
using anjk_api.Entities;
using anjk_api.Repositories;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace anjk_api.Services
{
    public class LiveService : ILiveService
    {
        private const string EnsureLiveUpdatesTableSql = @"
            CREATE TABLE IF NOT EXISTS ""LiveUpdates"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Message"" character varying(500) NOT NULL,
                ""CreatedOn"" timestamp with time zone NOT NULL DEFAULT NOW()
            );";

        private static readonly SemaphoreSlim EnsureLiveUpdatesTableLock = new(1, 1);
        private static volatile bool _liveUpdatesTableReady;

        private readonly AppDbContext _dbContext;
        private readonly IHubContext<LiveHub> _hubContext;
        private readonly ILogger<LiveService> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public LiveService(AppDbContext dbContext, IHubContext<LiveHub> hubContext, ILogger<LiveService> logger, IUnitOfWork unitOfWork)
        {
            _dbContext = dbContext;
            _hubContext = hubContext;
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        public async Task<LiveUpdate> SendLiveMessageAsync(string message)
        {
            await EnsureLiveUpdatesTableAsync();

            var liveUpdate = new LiveUpdate
            {
                Message = message,
                CreatedOn = DateTime.UtcNow
            };

            await _unitOfWork.Repository<LiveUpdate>().AddAsync(liveUpdate);
            await _unitOfWork.CompleteAsync();

            await _hubContext.Clients.All.SendAsync("ReceiveLiveUpdate", liveUpdate.Message);
            return liveUpdate;
        }

        public async Task<LiveUpdate?> GetCurrentAsync()
        {
            try
            {
                var history = await GetHistoryAsync(1);
                return history.FirstOrDefault();
            }
            catch (Exception ex) when (IsTransientOrMissingLiveTable(ex))
            {
                _logger.LogWarning(ex, "Returning no current live update because the live updates store is temporarily unavailable.");
                return null;
            }
        }

        public async Task<IEnumerable<LiveUpdate>> GetHistoryAsync(int take = 20)
        {
            try
            {
                await EnsureLiveUpdatesTableAsync();

                return await _dbContext.LiveUpdates
                    .AsNoTracking()
                    .OrderByDescending(item => item.CreatedOn)
                    .Take(take)
                    .ToListAsync();
            }
            catch (Exception ex) when (IsTransientOrMissingLiveTable(ex))
            {
                _logger.LogWarning(ex, "Returning empty live history because the live updates store is temporarily unavailable.");
                return Array.Empty<LiveUpdate>();
            }
        }

        private Task EnsureLiveUpdatesTableAsync()
        {
            return EnsureLiveUpdatesTableCoreAsync();
        }

        private async Task EnsureLiveUpdatesTableCoreAsync()
        {
            if (_liveUpdatesTableReady)
            {
                return;
            }

            await EnsureLiveUpdatesTableLock.WaitAsync();
            try
            {
                if (_liveUpdatesTableReady)
                {
                    return;
                }

                await _dbContext.Database.ExecuteSqlRawAsync(EnsureLiveUpdatesTableSql);
                _liveUpdatesTableReady = true;
            }
            finally
            {
                EnsureLiveUpdatesTableLock.Release();
            }
        }

        private static bool IsTransientOrMissingLiveTable(Exception ex)
        {
            if (ex is PostgresException postgresException && postgresException.SqlState == "42P01")
            {
                return true;
            }

            if (ex is NpgsqlException)
            {
                return true;
            }

            return ex is InvalidOperationException && ex.InnerException is NpgsqlException;
        }
    }
}
